#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class Alumno
	{
		private int idAlumno;
		public virtual int IdAlumno
		{
			get
			{
				return this.idAlumno;
			}
			set
			{
				this.idAlumno = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string apellido;
		public virtual string Apellido
		{
			get
			{
				return this.apellido;
			}
			set
			{
				this.apellido = value;
			}
		}
		
		private string dni;
		public virtual string Dni
		{
			get
			{
				return this.dni;
			}
			set
			{
				this.dni = value;
			}
		}
		
		private DateTime? fechaNacimiento;
		public virtual DateTime? FechaNacimiento
		{
			get
			{
				return this.fechaNacimiento;
			}
			set
			{
				this.fechaNacimiento = value;
			}
		}
		
		private int? idEscuela;
		public virtual int? IdEscuela
		{
			get
			{
				return this.idEscuela;
			}
			set
			{
				this.idEscuela = value;
			}
		}
		
		private int? idGrado;
		public virtual int? IdGrado
		{
			get
			{
				return this.idGrado;
			}
			set
			{
				this.idGrado = value;
			}
		}
		
		private long? telefono;
		public virtual long? Telefono
		{
			get
			{
				return this.telefono;
			}
			set
			{
				this.telefono = value;
			}
		}
		
		private string turno;
		public virtual string Turno
		{
			get
			{
				return this.turno;
			}
			set
			{
				this.turno = value;
			}
		}
		
		private bool? libretaSanitaria;
		public virtual bool? LibretaSanitaria
		{
			get
			{
				return this.libretaSanitaria;
			}
			set
			{
				this.libretaSanitaria = value;
			}
		}
		
		private string mail;
		public virtual string Mail
		{
			get
			{
				return this.mail;
			}
			set
			{
				this.mail = value;
			}
		}
		
		private string direccion;
		public virtual string Direccion
		{
			get
			{
				return this.direccion;
			}
			set
			{
				this.direccion = value;
			}
		}
		
		private string ciudad;
		public virtual string Ciudad
		{
			get
			{
				return this.ciudad;
			}
			set
			{
				this.ciudad = value;
			}
		}
		
		private bool? activo;
		public virtual bool? Activo
		{
			get
			{
				return this.activo;
			}
			set
			{
				this.activo = value;
			}
		}
		
		private string nombrePadre;
		public virtual string NombrePadre
		{
			get
			{
				return this.nombrePadre;
			}
			set
			{
				this.nombrePadre = value;
			}
		}
		
		private string nombreMadre;
		public virtual string NombreMadre
		{
			get
			{
				return this.nombreMadre;
			}
			set
			{
				this.nombreMadre = value;
			}
		}
		
		private int? idTipoAlumno;
		public virtual int? IdTipoAlumno
		{
			get
			{
				return this.idTipoAlumno;
			}
			set
			{
				this.idTipoAlumno = value;
			}
		}
		
		private string observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this.observaciones;
			}
			set
			{
				this.observaciones = value;
			}
		}
		
		private Escuela escuela;
		public virtual Escuela Escuela
		{
			get
			{
				return this.escuela;
			}
			set
			{
				this.escuela = value;
			}
		}
		
		private Grado grado;
		public virtual Grado Grado
		{
			get
			{
				return this.grado;
			}
			set
			{
				this.grado = value;
			}
		}
		
		private TipoDeAlumno tipoDeAlumno;
		public virtual TipoDeAlumno TipoDeAlumno
		{
			get
			{
				return this.tipoDeAlumno;
			}
			set
			{
				this.tipoDeAlumno = value;
			}
		}
		
		private IList<AutorizadosXAlumno> autorizadosXAlumnos = new List<AutorizadosXAlumno>();
		public virtual IList<AutorizadosXAlumno> AutorizadosXAlumnos
		{
			get
			{
				return this.autorizadosXAlumnos;
			}
		}
		
		private IList<GrupoFamiliarXAlumno> grupoFamiliarXAlumnos = new List<GrupoFamiliarXAlumno>();
		public virtual IList<GrupoFamiliarXAlumno> GrupoFamiliarXAlumnos
		{
			get
			{
				return this.grupoFamiliarXAlumnos;
			}
		}
		
		private IList<Inscripcion> inscripcions = new List<Inscripcion>();
		public virtual IList<Inscripcion> Inscripcions
		{
			get
			{
				return this.inscripcions;
			}
		}
		
		private IList<Pago> pagos = new List<Pago>();
		public virtual IList<Pago> Pagos
		{
			get
			{
				return this.pagos;
			}
		}
		
	}
}
#pragma warning restore 1591
