#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class AutorizadosXAlumno
	{
		private int idAutorizadoXAlumno;
		public virtual int IdAutorizadoXAlumno
		{
			get
			{
				return this.idAutorizadoXAlumno;
			}
			set
			{
				this.idAutorizadoXAlumno = value;
			}
		}
		
		private int? idAlumno;
		public virtual int? IdAlumno
		{
			get
			{
				return this.idAlumno;
			}
			set
			{
				this.idAlumno = value;
			}
		}
		
		private int? idAutorizado;
		public virtual int? IdAutorizado
		{
			get
			{
				return this.idAutorizado;
			}
			set
			{
				this.idAutorizado = value;
			}
		}
		
		private int? idParentesco;
		public virtual int? IdParentesco
		{
			get
			{
				return this.idParentesco;
			}
			set
			{
				this.idParentesco = value;
			}
		}
		
		private Parentesco parentesco;
		public virtual Parentesco Parentesco
		{
			get
			{
				return this.parentesco;
			}
			set
			{
				this.parentesco = value;
			}
		}
		
		private Alumno alumno;
		public virtual Alumno Alumno
		{
			get
			{
				return this.alumno;
			}
			set
			{
				this.alumno = value;
			}
		}
		
		private Autorizado autorizado;
		public virtual Autorizado Autorizado
		{
			get
			{
				return this.autorizado;
			}
			set
			{
				this.autorizado = value;
			}
		}
		
	}
}
#pragma warning restore 1591
