#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class Autorizado
	{
		private int idAutorizado;
		public virtual int IdAutorizado
		{
			get
			{
				return this.idAutorizado;
			}
			set
			{
				this.idAutorizado = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string apellido;
		public virtual string Apellido
		{
			get
			{
				return this.apellido;
			}
			set
			{
				this.apellido = value;
			}
		}
		
		private long? telefonoFijo;
		public virtual long? TelefonoFijo
		{
			get
			{
				return this.telefonoFijo;
			}
			set
			{
				this.telefonoFijo = value;
			}
		}
		
		private long? telefonoCelular;
		public virtual long? TelefonoCelular
		{
			get
			{
				return this.telefonoCelular;
			}
			set
			{
				this.telefonoCelular = value;
			}
		}
		
		private string direccion;
		public virtual string Direccion
		{
			get
			{
				return this.direccion;
			}
			set
			{
				this.direccion = value;
			}
		}
		
		private string mail;
		public virtual string Mail
		{
			get
			{
				return this.mail;
			}
			set
			{
				this.mail = value;
			}
		}
		
		private IList<AutorizadosXAlumno> autorizadosXAlumnos = new List<AutorizadosXAlumno>();
		public virtual IList<AutorizadosXAlumno> AutorizadosXAlumnos
		{
			get
			{
				return this.autorizadosXAlumnos;
			}
		}
		
	}
}
#pragma warning restore 1591
