#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class ConceptoXCurso
	{
		private int idConceptoXCurso;
		public virtual int IdConceptoXCurso
		{
			get
			{
				return this.idConceptoXCurso;
			}
			set
			{
				this.idConceptoXCurso = value;
			}
		}
		
		private int? idCurso;
		public virtual int? IdCurso
		{
			get
			{
				return this.idCurso;
			}
			set
			{
				this.idCurso = value;
			}
		}
		
		private int? idConcepto;
		public virtual int? IdConcepto
		{
			get
			{
				return this.idConcepto;
			}
			set
			{
				this.idConcepto = value;
			}
		}
		
		private Curso curso;
		public virtual Curso Curso
		{
			get
			{
				return this.curso;
			}
			set
			{
				this.curso = value;
			}
		}
		
		private Concepto concepto;
		public virtual Concepto Concepto
		{
			get
			{
				return this.concepto;
			}
			set
			{
				this.concepto = value;
			}
		}
		
	}
}
#pragma warning restore 1591
