#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class ConceptoXAlumnoResultSet0
	{
		private int _idConcepto;
		public virtual int idConcepto
		{
			get
			{
				return this._idConcepto;
			}
			set
			{
				this._idConcepto = value;
			}
		}
		
		private decimal? _valorConcepto;
		public virtual decimal? valorConcepto
		{
			get
			{
				return this._valorConcepto;
			}
			set
			{
				this._valorConcepto = value;
			}
		}
		
		private int _idTipoDeConcepto;
		public virtual int idTipoDeConcepto
		{
			get
			{
				return this._idTipoDeConcepto;
			}
			set
			{
				this._idTipoDeConcepto = value;
			}
		}
		
		private string _tipoDeConcepto;
		public virtual string TipoDeConcepto
		{
			get
			{
				return this._tipoDeConcepto;
			}
			set
			{
				this._tipoDeConcepto = value;
			}
		}
		
		private string _concepto;
		public virtual string concepto
		{
			get
			{
				return this._concepto;
			}
			set
			{
				this._concepto = value;
			}
		}
		
	}
}
#pragma warning restore 1591
