#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class Cursada
	{
		private int idCursada;
		public virtual int IdCursada
		{
			get
			{
				return this.idCursada;
			}
			set
			{
				this.idCursada = value;
			}
		}
		
		private int? idCurso;
		public virtual int? IdCurso
		{
			get
			{
				return this.idCurso;
			}
			set
			{
				this.idCurso = value;
			}
		}
		
		private DateTime? fechaInicio;
		public virtual DateTime? FechaInicio
		{
			get
			{
				return this.fechaInicio;
			}
			set
			{
				this.fechaInicio = value;
			}
		}
		
		private DateTime? fechaFin;
		public virtual DateTime? FechaFin
		{
			get
			{
				return this.fechaFin;
			}
			set
			{
				this.fechaFin = value;
			}
		}
		
		private bool? activo;
		public virtual bool? Activo
		{
			get
			{
				return this.activo;
			}
			set
			{
				this.activo = value;
			}
		}
		
		private Curso curso;
		public virtual Curso Curso
		{
			get
			{
				return this.curso;
			}
			set
			{
				this.curso = value;
			}
		}
		
		private IList<Inscripcion> inscripcions = new List<Inscripcion>();
		public virtual IList<Inscripcion> Inscripcions
		{
			get
			{
				return this.inscripcions;
			}
		}
		
	}
}
#pragma warning restore 1591
