#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class DevuelveConceptoXCursoResultSet0
	{
		private int _idConceptoXCurso;
		public virtual int idConceptoXCurso
		{
			get
			{
				return this._idConceptoXCurso;
			}
			set
			{
				this._idConceptoXCurso = value;
			}
		}
		
		private string _nombreTipoConcepto;
		public virtual string nombreTipoConcepto
		{
			get
			{
				return this._nombreTipoConcepto;
			}
			set
			{
				this._nombreTipoConcepto = value;
			}
		}
		
		private int _idConcepto;
		public virtual int idConcepto
		{
			get
			{
				return this._idConcepto;
			}
			set
			{
				this._idConcepto = value;
			}
		}
		
		private string _nombreConcepto;
		public virtual string nombreConcepto
		{
			get
			{
				return this._nombreConcepto;
			}
			set
			{
				this._nombreConcepto = value;
			}
		}
		
	}
}
#pragma warning restore 1591
