#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class DevuelveMesAPagarResultSet0
	{
		private int _idMes;
		public virtual int idMes
		{
			get
			{
				return this._idMes;
			}
			set
			{
				this._idMes = value;
			}
		}
		
		private string _nombre;
		public virtual string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private decimal? _saldo;
		public virtual decimal? saldo
		{
			get
			{
				return this._saldo;
			}
			set
			{
				this._saldo = value;
			}
		}
		
		private decimal? _valorConcepto;
		public virtual decimal? valorConcepto
		{
			get
			{
				return this._valorConcepto;
			}
			set
			{
				this._valorConcepto = value;
			}
		}
		
	}
}
#pragma warning restore 1591
