#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class GrupoFamiliar
	{
		private int idGrupoFamiliar;
		public virtual int IdGrupoFamiliar
		{
			get
			{
				return this.idGrupoFamiliar;
			}
			set
			{
				this.idGrupoFamiliar = value;
			}
		}
		
		private string nombreGrupoFamiliar;
		public virtual string NombreGrupoFamiliar
		{
			get
			{
				return this.nombreGrupoFamiliar;
			}
			set
			{
				this.nombreGrupoFamiliar = value;
			}
		}
		
		private IList<GrupoFamiliarXAlumno> grupoFamiliarXAlumnos = new List<GrupoFamiliarXAlumno>();
		public virtual IList<GrupoFamiliarXAlumno> GrupoFamiliarXAlumnos
		{
			get
			{
				return this.grupoFamiliarXAlumnos;
			}
		}
		
	}
}
#pragma warning restore 1591
