#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class GrupoFamiliarXAlumno
	{
		private int idGrupoFamiliarXAlumno;
		public virtual int IdGrupoFamiliarXAlumno
		{
			get
			{
				return this.idGrupoFamiliarXAlumno;
			}
			set
			{
				this.idGrupoFamiliarXAlumno = value;
			}
		}
		
		private int? idGrupoFamiliar;
		public virtual int? IdGrupoFamiliar
		{
			get
			{
				return this.idGrupoFamiliar;
			}
			set
			{
				this.idGrupoFamiliar = value;
			}
		}
		
		private int? idAlumno;
		public virtual int? IdAlumno
		{
			get
			{
				return this.idAlumno;
			}
			set
			{
				this.idAlumno = value;
			}
		}
		
		private GrupoFamiliar grupoFamiliar;
		public virtual GrupoFamiliar GrupoFamiliar
		{
			get
			{
				return this.grupoFamiliar;
			}
			set
			{
				this.grupoFamiliar = value;
			}
		}
		
		private Alumno alumno;
		public virtual Alumno Alumno
		{
			get
			{
				return this.alumno;
			}
			set
			{
				this.alumno = value;
			}
		}
		
	}
}
#pragma warning restore 1591
