#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class ListaHermanosResultSet0
	{
		private int _idAlumno;
		public virtual int idAlumno
		{
			get
			{
				return this._idAlumno;
			}
			set
			{
				this._idAlumno = value;
			}
		}
		
		private string _hermanos;
		public virtual string Hermanos
		{
			get
			{
				return this._hermanos;
			}
			set
			{
				this._hermanos = value;
			}
		}
		
	}
}
#pragma warning restore 1591
