#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class ListaAutorizadosXAlumnoResultSet0
	{
		private int _idAutorizado;
		public virtual int idAutorizado
		{
			get
			{
				return this._idAutorizado;
			}
			set
			{
				this._idAutorizado = value;
			}
		}
		
		private string _autorizado;
		public virtual string Autorizado
		{
			get
			{
				return this._autorizado;
			}
			set
			{
				this._autorizado = value;
			}
		}
		
		private long? _telefonoFijo;
		public virtual long? TelefonoFijo
		{
			get
			{
				return this._telefonoFijo;
			}
			set
			{
				this._telefonoFijo = value;
			}
		}
		
		private long? _telefonoCelular;
		public virtual long? TelefonoCelular
		{
			get
			{
				return this._telefonoCelular;
			}
			set
			{
				this._telefonoCelular = value;
			}
		}
		
		private string _direccion;
		public virtual string Direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				this._direccion = value;
			}
		}
		
		private string _mail;
		public virtual string Mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				this._mail = value;
			}
		}
		
		private string _alumno;
		public virtual string Alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno = value;
			}
		}
		
		private string _relacion;
		public virtual string Relacion
		{
			get
			{
				return this._relacion;
			}
			set
			{
				this._relacion = value;
			}
		}
		
	}
}
#pragma warning restore 1591
