#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class ListaInscripcionesResultSet0
	{
		private int _idInscripcion;
		public virtual int idInscripcion
		{
			get
			{
				return this._idInscripcion;
			}
			set
			{
				this._idInscripcion = value;
			}
		}
		
		private string _nombre;
		public virtual string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _apellido;
		public virtual string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				this._apellido = value;
			}
		}
		
		private string _curso;
		public virtual string curso
		{
			get
			{
				return this._curso;
			}
			set
			{
				this._curso = value;
			}
		}
		
		private DateTime? _fechaInscripcion;
		public virtual DateTime? fechaInscripcion
		{
			get
			{
				return this._fechaInscripcion;
			}
			set
			{
				this._fechaInscripcion = value;
			}
		}
		
		private string _observaciones;
		public virtual string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				this._observaciones = value;
			}
		}
		
	}
}
#pragma warning restore 1591
