#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class Parentesco
	{
		private int idParentesco;
		public virtual int IdParentesco
		{
			get
			{
				return this.idParentesco;
			}
			set
			{
				this.idParentesco = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private IList<AutorizadosXAlumno> autorizadosXAlumnos = new List<AutorizadosXAlumno>();
		public virtual IList<AutorizadosXAlumno> AutorizadosXAlumnos
		{
			get
			{
				return this.autorizadosXAlumnos;
			}
		}
		
	}
}
#pragma warning restore 1591
