#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class ReportePagosXDiaResultSet0
	{
		private string _alumno;
		public virtual string Alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno = value;
			}
		}
		
		private decimal? _pago;
		public virtual decimal? Pago
		{
			get
			{
				return this._pago;
			}
			set
			{
				this._pago = value;
			}
		}
		
		private string _concepto;
		public virtual string Concepto
		{
			get
			{
				return this._concepto;
			}
			set
			{
				this._concepto = value;
			}
		}
		
		private string _meses;
		public virtual string Meses
		{
			get
			{
				return this._meses;
			}
			set
			{
				this._meses = value;
			}
		}
		
	}
}
#pragma warning restore 1591
