#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class ReporteDePagosMensualesResultSet0
	{
		private string _alumno;
		public virtual string Alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno = value;
			}
		}
		
		private decimal? _valorConcepto;
		public virtual decimal? ValorConcepto
		{
			get
			{
				return this._valorConcepto;
			}
			set
			{
				this._valorConcepto = value;
			}
		}
		
		private string _marzo;
		public virtual string Marzo
		{
			get
			{
				return this._marzo;
			}
			set
			{
				this._marzo = value;
			}
		}
		
		private string _abril;
		public virtual string Abril
		{
			get
			{
				return this._abril;
			}
			set
			{
				this._abril = value;
			}
		}
		
		private string _mayo;
		public virtual string Mayo
		{
			get
			{
				return this._mayo;
			}
			set
			{
				this._mayo = value;
			}
		}
		
		private string _junio;
		public virtual string Junio
		{
			get
			{
				return this._junio;
			}
			set
			{
				this._junio = value;
			}
		}
		
		private string _julio;
		public virtual string Julio
		{
			get
			{
				return this._julio;
			}
			set
			{
				this._julio = value;
			}
		}
		
		private string _agosto;
		public virtual string Agosto
		{
			get
			{
				return this._agosto;
			}
			set
			{
				this._agosto = value;
			}
		}
		
		private string _setiembre;
		public virtual string Setiembre
		{
			get
			{
				return this._setiembre;
			}
			set
			{
				this._setiembre = value;
			}
		}
		
		private string _octubre;
		public virtual string Octubre
		{
			get
			{
				return this._octubre;
			}
			set
			{
				this._octubre = value;
			}
		}
		
		private string _noviembre;
		public virtual string Noviembre
		{
			get
			{
				return this._noviembre;
			}
			set
			{
				this._noviembre = value;
			}
		}
		
		private string _diciembre;
		public virtual string Diciembre
		{
			get
			{
				return this._diciembre;
			}
			set
			{
				this._diciembre = value;
			}
		}
		
	}
}
#pragma warning restore 1591
