#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class ReportePagosXMesResultSet0
	{
		private int _idPago;
		public virtual int idPago
		{
			get
			{
				return this._idPago;
			}
			set
			{
				this._idPago = value;
			}
		}
		
		private string _alumno;
		public virtual string Alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno = value;
			}
		}
		
		private decimal? _valorAPagar;
		public virtual decimal? valorAPagar
		{
			get
			{
				return this._valorAPagar;
			}
			set
			{
				this._valorAPagar = value;
			}
		}
		
		private decimal? _saldo;
		public virtual decimal? Saldo
		{
			get
			{
				return this._saldo;
			}
			set
			{
				this._saldo = value;
			}
		}
		
		private int? _mes;
		public virtual int? Mes
		{
			get
			{
				return this._mes;
			}
			set
			{
				this._mes = value;
			}
		}
		
	}
}
#pragma warning restore 1591
